//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelMvc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelMvc.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching ending indexer &quot;]&quot; in binding path &quot;{0}&quot;..
        /// </summary>
        internal static string ErrorBindingPathInvalidIndexer {
            get {
                return ResourceManager.GetString("ErrorBindingPathInvalidIndexer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel.Application not found..
        /// </summary>
        internal static string ErrorExcelAppFound {
            get {
                return ResourceManager.GetString("ErrorExcelAppFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &quot;{0}&quot;  is neither a landscape nor a portrait table, table headers must be arranged as a row or a column..
        /// </summary>
        internal static string ErrorInvalidTableOrientation {
            get {
                return ResourceManager.GetString("ErrorInvalidTableOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid view type &quot;{0}&quot;. Must be either Form or Table..
        /// </summary>
        internal static string ErrorInvalidViewType {
            get {
                return ResourceManager.GetString("ErrorInvalidViewType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No &quot;Data Cell&quot; column in a view binding config table..
        /// </summary>
        internal static string ErrorNoBindingCellFound {
            get {
                return ResourceManager.GetString("ErrorNoBindingCellFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No binding found for property &quot;{0}&quot;..
        /// </summary>
        internal static string ErrorNoBindingForProperty {
            get {
                return ResourceManager.GetString("ErrorNoBindingForProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No &quot;Binding Mode&quot; column in a view binding config table..
        /// </summary>
        internal static string ErrorNoBindingModeFound {
            get {
                return ResourceManager.GetString("ErrorNoBindingModeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No &quot;Binding Path&quot; column in a view binding config table..
        /// </summary>
        internal static string ErrorNoBindingPathFound {
            get {
                return ResourceManager.GetString("ErrorNoBindingPathFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No command name &quot;{0}&quot; found in &quot;{1}&quot;..
        /// </summary>
        internal static string ErrorNoCommandNameFound {
            get {
                return ResourceManager.GetString("ErrorNoCommandNameFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data cell &quot;{0}&quot; does not point to a valid Range..
        /// </summary>
        internal static string ErrorNoDataCellRange {
            get {
                return ResourceManager.GetString("ErrorNoDataCellRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model {0} to View {1} does not implment IEnumerable interface..
        /// </summary>
        internal static string ErrorNoIEnumuerable {
            get {
                return ResourceManager.GetString("ErrorNoIEnumuerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} (get) does not exist on {1}..
        /// </summary>
        internal static string ErrorNoPropertyGet {
            get {
                return ResourceManager.GetString("ErrorNoPropertyGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} (set) does not exist on {1}..
        /// </summary>
        internal static string ErrorNoPropertySet {
            get {
                return ResourceManager.GetString("ErrorNoPropertySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No view name specifed in &quot;{0}&quot;..
        /// </summary>
        internal static string ErrorNoViewNameFound {
            get {
                return ResourceManager.GetString("ErrorNoViewNameFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &quot;{0}&quot; (type {1}, parent {2}) created..
        /// </summary>
        internal static string InfoCmdCreated {
            get {
                return ResourceManager.GetString("InfoCmdCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View &quot;{0}&quot; (type {1}, parent {2}) created..
        /// </summary>
        internal static string InfoViewCreated {
            get {
                return ResourceManager.GetString("InfoViewCreated", resourceCulture);
            }
        }
    }
}
